
spring:
  redis:
    host: 192.168.190.188
    port: 6379
    password: 11111
    lettuce: # 即使使用jedis也不会使用 jedis-pool
      pool:
        max-active: 200
        max-idle: 10
        max-wait: 10ms # 最大阻塞等待时间
        min-idle: 5
    timeout: 1000
server:
  port: 8003